
import { GoogleGenAI } from "@google/genai";
import type { GenerateImageResponse } from "@google/genai";


export interface GenerationConfig {
    prompt: string;
    aspectRatio: '1:1' | '16:9' | '9:16' | '4:3' | '3:4';
    numberOfImages: number;
}

/**
 * Generates an image using the Gemini API (imagen-4.0-generate-001 model).
 * @param config The configuration for the image generation.
 * @returns A promise that resolves to the base64 encoded string of the generated image.
 */
export const generateImage = async (config: GenerationConfig): Promise<string> => {
    // This check is for the browser environment where process.env is not directly available.
    // The build tool should replace process.env.API_KEY with the actual key.
    // In a real-world scenario, this key would be handled securely.
    if (!process.env.API_KEY) {
        console.error("API_KEY environment variable not set.");
        throw new Error("API key is not configured.");
    }
    
    const ai = new GoogleGenAI({ apiKey: process.env.API_KEY });

    try {
        const response: GenerateImageResponse = await ai.models.generateImages({
            model: 'imagen-4.0-generate-001',
            prompt: config.prompt,
            config: {
                numberOfImages: 1, // API currently supports 1. Adjust if needed.
                outputMimeType: 'image/jpeg',
                aspectRatio: config.aspectRatio,
            },
        });

        if (response.generatedImages && response.generatedImages.length > 0) {
            const base64ImageBytes: string = response.generatedImages[0].image.imageBytes;
            return `data:image/jpeg;base64,${base64ImageBytes}`;
        } else {
            throw new Error("No image was generated by the API.");
        }
    } catch (error) {
        console.error("Error generating image with Gemini API:", error);
        // You might want to handle specific error types from the API here
        throw new Error("Failed to generate image. Please try again later.");
    }
};
